test:
  stage: test
  image: python:3.12.12-trixie
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python contrib/ci_test.py
  artifacts:
    paths:
      - reports/
      - models/
      - mlruns/
