test:
  stage: test
  image: python:3.12.12-trixie
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python ml_pipeline.py
  artifacts:
    paths:
      - reports/
      - models/
      - mlruns/
